#!/usr/bin/env python

"""
Setup script for ArniePye.
"""

import sys
from subprocess import Popen, PIPE
import setuptools

from sublimebootstrap import PROJECT, CLI

# Append the Python main version number to the end of the CLI name
CLIN = CLI + str(sys.version_info[0])


# Determine version from Git
version = None
try:
    # Attempt to try to get the version string using 'git describe'.
    describe = 'git describe --abbrev=8 --dirty'
    version = Popen(describe.split(), stdout=PIPE).communicate()[0].strip()
except:
    try:
        # Try to get the version from 'sublimebootstrap/__version__.py'.
        from sublimebootstrap import __version__
        version = __version__.version
    except:
        version = None


# Update the version if it was successfully determined
if version:
    # Strip off hash and -dirty flags
    parts = version.split('-')
    if len(parts) > 1:
        version = '-r'.join(parts[0:2])

    # Write the version string to 'sublimebootstrap/__version__.py'
    with open('sublimebootstrap/__version__.py', 'w') as f:
        f.write('#!/usr/bin/env python\n')
        f.write('# This file is autogenerated by setup.py\n')
        f.write('version = "{0}"\n'.format(version))

# Import version for setuptools from the __version__.py file
try:
    # Try to get the version from 'sublimebootstrap/__version__.py'.
    from sublimebootstrap import __version__
    version = __version__.version
except ImportError:
    version = 'unknown'


setuptools.setup(
    name=PROJECT,
    version=version,

    description="A small program to easily set up a Sublime Text project file..",
    url='http://github.com/joshfriend/sublime-bootstrap',
    author='Josh Friend',
    author_email='josh@fueledbycaffeine.com',

    packages=['sublimebootstrap'],
    package_data={'sublimebootstrap': ['data/*']},

    entry_points={'console_scripts': [CLI + ' = sublimebootstrap.cli:main',
                                      CLIN + ' = sublimebootstrap.cli:main']},

    long_description=open('README.md').read(),
    install_requires=open('requirements.txt').read(),
)
